theme: jekyll-theme-slate
title: Tensho
email: andrew.babichev@gmail.com
description: Заметки непутевого программиста
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title'
  sort_reverse: true
  trail:
    before: 2
    after: 2

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
