theme: jekyll-theme-slate
title: Tensho
email: andrew.babichev@gmail.com
description: Заметки непутевого программиста
paginate: 5
paginate_path: "/page/:num"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

plugins:
  - jekyll-feed
  - jekyll-paginate
