theme: jekyll-theme-slate
title: Tensho
email: andrew.babichev@gmail.com
description: Заметки непутевого программиста

ga_id: UA-127561266-1

# Exclude directories and/or files from the conversion
exclude:
  - .idea
  - .circleci
  - bin
  - vendor # bundle install --deployment
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - assets/*.puml
# Make future date post visible
# https://stackoverflow.com/questions/30625044/jekyll-post-not-generated
future: true

# jekyll-paginate
paginate: 5
paginate_path: "/page/:num"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

jekyll-spaceship:
  processors:
    - plantuml-processor
